apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mendix
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mendix-app
    spec:
      containers:
      - name: mendix-app
        image: casalinas83/mendix:v1
        ports:
        - name: http-port
          containerPort: 80
        env:
          - name: ADMIN_PASSWORD
            value: Password1!
          - name: DATABASE_ENDPOINT
            value: postgres://mendix:mendix@mendix-db-service/mendix
          - name: LICENSE_ID
            valueFrom:
              secretKeyRef:
                name: mendix-secrets
                key: license_id
          - name: LICENSE_KEY
            valueFrom:
              secretKeyRef:
                name: mendix-secrets
                key: license_key
        volumeMounts:
          - mountPath: "/build/data/files"
            name: "mendix-storage"
      volumes:
        - name: mendix-storage
          persistentVolumeClaim:
            claimName: mendix-storage