apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mendix-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mendix-db
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
            - name: db-port
              containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: mendix
          - name: POSTGRES_PASSWORD
            value: mendix
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: "mendix-pgdata"
      volumes:
            - hostPath:
                path: "/home/docker/pgdata"
              name: mendix-pgdata
